### ISSUE TITLE
log功能优化

### ISSUE THREAD

**Issue by NekodRider** [NekodRider/mirai-qbot#52]
- [ ] 权限机制。log功能应当只对部分给定(有权限)用户私聊提供。等待用户系统完成 #68 
- [ ] 文件发送机制。消息文本不便于阅读，考虑以文件形式发送log文件。等待 mirai 支持 https://github.com/mamoe/mirai/issues/639
- [x] logger机制优化，独立记录到logs文件夹。 #65 重构时已完成
